<a href="https://colab.research.google.com/github/KhuzaimaHassan/IT-Training/blob/main/4th-Class/4th_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def greet(name):
  print('Hello')
say_hello=greet
say_hello('Hello')

Hello


In [ ]:
def apply_func(func,value):
  return func(value)
print(apply_func(lambda x:x*2,10))

20


In [ ]:
def multiplier(factor):
  def multiply(num):
    return num*factor
  return multiply
multiply5=multiplier(5)
print(multiply5(10))

50


In [ ]:
def factorial(n):
  if n==0:
    return 1
  return n*factorial(n-1)
print(factorial(5))

120


In [ ]:
def greet(name):
  """Greets a person"""
  print(f'Hello {name}')
greet('John')


help(greet)

Hello John
Help on function greet in module __main__:

greet(name)
    Greets a person



In [ ]:
#Local Variable
def my_function():
  x=10
  print('Inside Function',x)

my_function()

Inside Function 10


In [ ]:
#Global Variable
y=20
def my_function():
  print('Inside Function',y)

my_function()
print('Outside Function',y)

Inside Function 20
Outside Function 20


In [ ]:
z=5
def modify_global():
  global z
  z=10
  print('Inside Function',z)

modify_global()
print('Outside Function',z)

Inside Function 10
Outside Function 10


In [ ]:

def outer():
  x=5
  def inner():
    nonlocal x
    x=10
  inner()
  print('Outer function x:',x)

outer()


Outer function x: 10


In [ ]:
y=50

def test():
  y=10
  print(y)

test()
print(y)

10
50


In [ ]:
import numpy as np
py_list=[1,2,3,4]
np_array=np.array(py_list)

print(type(py_list))
print(type(np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
arr_id=np.array([1,2,3,4,5])
print(arr_id)

[1 2 3 4 5]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)

[[1 2 3]
 [4 5 6]]
2


In [ ]:
zeros_array=np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones_array=np.ones((2,3))
print(ones_array)
print(ones_array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]]
2


In [ ]:
full_array=np.full((2,3),7)
print(full_array)

[[7 7 7]
 [7 7 7]]


In [ ]:
linespace_array=np.linspace(1,10,5)
print(linespace_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
range_array=np.arange(1,10,2)
print(range_array)

[1 3 5 7 9]


In [ ]:
range_array=np.random.rand(3,3)
print(range_array)

[[0.92903112 0.07972294 0.53339461]
 [0.56364823 0.23235696 0.73477218]
 [0.88081015 0.61637308 0.45157549]]


In [ ]:
random_int_array=np.random.randint(1,100,(3,3))
print(random_int_array)

[[ 5 89 71]
 [45  1 19]
 [95 30 43]]


In [ ]:
arr=np.array([[1,2,3,4],[4,4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.size)

(2, 4)
2
8


In [ ]:
arr=np.array([1,2,3,4,5,6])
print(arr.ndim)
reshaped_arr=arr.reshape(2,3)
print(reshaped_arr)
print(reshaped_arr.ndim)

1
[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr=np.array([1,2,3,4,5,6])
arr_2=np.array([7,8,9,10,11,12])
print(arr+arr_2)
print(arr-arr_2)
print(arr*arr_2)
print(arr/arr_2)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
[0.14285714 0.25       0.33333333 0.4        0.45454545 0.5       ]


In [ ]:
arr=np.array([0,np.pi/2,np.pi])
print(arr)
print(np.sin(arr))
print(np.exp(arr))
print(np.sqrt(arr+1))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.          4.81047738 23.14069263]
[1.         1.6033703  2.03509033]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr))

1
6
21


In [ ]:
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[2])
print(arr[-1])
print(arr[-3])

10
30
50
30


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[0,1])
print(arr_2d[2,2])
print(arr_2d[-1,0])

2
9
7


In [ ]:
arr=np.array([10,20,30,40,50,60,70])

print(arr[1:5])
print(arr[:4])
print(arr[3:])
print(arr[::2])
print(arr[::-1])

[20 30 40 50]
[10 20 30 40]
[40 50 60 70]
[10 30 50 70]
[70 60 50 40 30 20 10]


In [ ]:
arr_2d=np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]])
print(arr_2d[0:2,1:3])

[[2 3]
 [6 7]]


In [ ]:
print(arr_2d[:,2])
print(arr_2d[1,:])
print(arr_2d[:,::2])

[ 3  7 11]
[5 6 7 8]
[[ 1  3]
 [ 5  7]
 [ 9 11]]


In [ ]:
arr=np.array([10,20,30,40,50])
result=np.where(arr>25)
print(result)

filtered_values=arr[np.where(arr>25)]
print(filtered_values)

(array([2, 3, 4]),)
[30 40 50]


In [ ]:
arr=np.array([10,20,30,40,50])
print(np.take(arr,[0,2,4]))

[10 30 50]


In [ ]:
arr=np.array([10,20,30,40,50])
np.put(arr,[1,3],[99,77])
print(arr)

[10 99 30 77 50]
